services:
  fastapi:
    build:
      context: .
      dockerfile: ./endpoints/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      consumer:
        condition: service_started
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: ./outbox_processor/Dockerfile
    depends_on:
      consumer:
        condition: service_started
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  consumer:
    build: .
    command: >
      sh -c "alembic upgrade head && python -m rabbit_consumer.consumer"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    hostname: my-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_NODE_IP_ADDRESS: ${RABBITMQ_HOST}
      RABBITMQ_NODE_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5